container_image        = osdf:///chtc/staging/<NetID>/genomics_tutorial/software/minimap2_08OCT2025_v1.sif

executable		       = ./executables/minimap2_index.sh
arguments              = <input_ref_genome_fasta_file_name>

transfer_input_files   = ./inputs/<input_ref_genome_fasta_file_name>

transfer_output_files  = <input_ref_genome_fasta_file_name>.mmi
transfer_output_remaps = "<input_ref_genome_fasta_file_name>.mmi = \
                          /staging/<NetID>/genomics_tutorial/inputs/<input_ref_genome_fasta_file_name>.mmi"

output                 = ./logs/$(Cluster)_$(Process)_minimap2_indexing_step1.out
error                  = ./logs/$(Cluster)_$(Process)_minimap2_indexing_step1.err
log                    = ./logs/$(Cluster)_minimap2_indexing_step1.log

request_cpus           = 4
request_disk           = 10 GB
request_memory         = 24 GB

queue 1